apiVersion: skaffold/v4beta3
kind: Config
manifests:
   rawYaml:
     - ./infra/k8s/*
build:
  # local:
  #   push: false  #to prevent pushing to docker hub
  googleCloudBuild: 
    projectId: ticketing-417910
  artifacts:
    - image: us.gcr.io/ticketing-417910/auth
      context: auth   #folder that contains all the code for the image
      docker: 
        dockerfile: Dockerfile
      sync:                                  
        manual:
          - src: 'src/**/*.ts' #tells how to handle the changes , tells to watch src directory of all files that endes with .ts and set destination to the corresponding path inside the container
            dest: .                         
        
        
  